generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ocs-operator-patch
    namespace: okd-team
    files:
      - repo.patch
      - remove-reliance-on-podman-run.patch

resources:
  - repository.yaml
  - pvc.yaml