generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: gitops-console-plugin-patch
    namespace: okd-team
    files:
      - repo.patch

resources:
  - repository.yaml
  - volume.yaml