generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: log-file-metric-exporter-patch
    namespace: okd-team
    files:
      - repo.patch

resources:
  - repository.yaml
  - pvc.yaml