apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-file-metric-exporter-volume
  namespace: okd-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi