apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: operator-golang
  namespace: okd-team
spec:
  params:
    - name: repo-url
      description: The repo url
      type: string
    - name: repo-ref
      description: The repo ref
      type: string
    - name: base-image-registry
      description: The base image registry
      type: string
    - name: image-name
      description: The image name
      type: string
  
  workspaces:
    - name: workspace
    - name: patches

  tasks:
    - name: clone-and-patch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.repo-ref)
        - name: verbose
          value: 'true'
        - name: subdirectory
          value: repository
      workspaces:
        - name: output
          workspace: workspace
        - name: patches
          workspace: patches

    - name: get-version
      runAfter: [ clone-and-patch ]
      taskRef:
        name: find-version
      params:
        - name: subdirectory
          value: repository
        - name: name
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: workspace

    - name: get-id
      runAfter: [ get-version ]
      taskRef:
        name: build-id
      params:
        - name: version
          value: $(tasks.get-version.results.version)

    - name: build-operator
      runAfter: [ clone-and-patch ]
      taskRef:
        name: make-build
      params:
        - name: subdirectory
          value: repository
      workspaces:
        - name: source
          workspace: workspace
        - name: build-cache-root
          workspace: workspace
        - name: build-pkg
          workspace: workspace

    - name: deploy-operator
      runAfter: [ build-operator, get-id ]
      taskRef:
        name: buildah
      params:
        - name: image
          value: $(params.base-image-registry)/$(params.image-name):v$(tasks.get-id.results.build-id)
        - name: subdirectory
          value: repository
      workspaces:
        - name: source
          workspace: workspace

    - name: build-bundle
      runAfter: [ deploy-operator ]
      taskRef:
        name: bundle
      params:
        - name: image-name
          value: $(params.image-name)
        - name: base-image-registry
          value: $(params.base-image-registry)
        - name: image-version
          value: $(tasks.get-id.results.build-id)
        - name: channel
          value: stable
        - name: default-channel
          value: stable
        - name: subdirectory
          value: repository
      workspaces:
        - name: source
          workspace: workspace
        - name: build-cache-root
          workspace: workspace
        - name: build-pkg
          workspace: workspace

    - name: deploy-bundle
      runAfter: [ build-bundle ]
      taskRef:
        name: buildah
      params:
        - name: image
          value: $(params.base-image-registry)/$(params.image-name)-bundle:v$(tasks.get-id.results.build-id)
        - name: dockerfile
          value: bundle.Dockerfile
        - name: subdirectory
          value: repository
      workspaces:
        - name: source
          workspace: workspace

#    - name: deploy-bundle
#      runAfter: [container-all]
#      taskRef:
#        name: bundle
#      params:
#        - name: repo-name
#          value: $(params.repo-name)
#        - name: base-image-registry
#          value: $(params.base-image-registry)
#        - name: bundle-version
#          value: $(params.bundle-version)
#        - name: channel
#          value: $(params.channel)
#        - name: default-channel
#          value: $(params.default-channel)
#        - name: catalog-image
#          value: $(params.catalog-image)
#      workspaces:
#        - name: src
#          workspace: shared-workspace
#        - name: build-cache-root
#          workspace: shared-workspace
