apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: operand
  namespace: okd-team
spec:
  params:
    - name: repo-url
      description: The repo url
      type: string
    - name: repo-ref
      description: The repo ref
      type: string
    - name: base-image-registry
      description: The base image registry
      type: string
    - name: image-name
      description: The image name
      type: string
    - name: image-version
      description: The image version
      type: string
    - name: build-image
      description: The build image
      type: string
      default: quay.io/okd/go-bundle-tools:v1.1.2
  
  workspaces:
    - name: workspace
    - name: patches
  
  tasks:
    - name: clone-and-patch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.repo-ref)
        - name: verbose
          value: 'true'
        - name: subdirectory
          value: repository
      workspaces:
        - name: output
          workspace: workspace
        - name: patches
          workspace: patches

    - name: install
      runAfter: [ clone-and-patch ]
      taskRef:
        name: make
      params:
        - name: image
          value: $(params.build-image)
        - name: subdirectory
          value: repository
        - name: args
          value: ["okd-install"]
      workspaces:
        - name: source
          workspace: workspace

    - name: build
      runAfter: [ install ]
      taskRef:
        name: make
      params:
        - name: image
          value: $(params.build-image)
        - name: subdirectory
          value: repository
        - name: args
          value: [ "okd-build" ]
      workspaces:
        - name: source
          workspace: workspace

    - name: test
      runAfter: [ build ]
      taskRef:
        name: make
      params:
        - name: image
          value: $(params.build-image)
        - name: subdirectory
          value: repository
        - name: args
          value: [ "okd-test" ]
      workspaces:
        - name: source
          workspace: workspace

    - name: e2e
      runAfter: [ test ]
      taskRef:
        name: make
      params:
        - name: image
          value: $(params.build-image)
        - name: subdirectory
          value: repository
        - name: args
          value: [ "okd-e2e" ]
      workspaces:
        - name: source
          workspace: workspace

    - name: image-build
      runAfter: [ e2e ]
      taskRef:
        name: buildah-build
      params:
        - name: image
          value: $(params.image-name)
        - name: subdirectory
          value: repository
      workspaces:
        - name: source
          workspace: workspace
        - name: containers
          workspace: workspace

    - name: image-push
      runAfter: [ image-build ]
      taskRef:
        name: buildah-push
      params:
        - name: image
          value: $(params.image-name)
        - name: remote
          value: $(params.base-image-registry)/$(params.image-name):v$(params.image-version)
      workspaces:
        - name: containers
          workspace: workspace
