apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: operand
  namespace: okd-team
spec:
  params:
    - name: repo-url
      description: The repo url
      type: string
    - name: repo-ref
      description: The repo ref
      type: string
    - name: base-image-registry
      description: The base image registry
      type: string
    - name: image-name
      description: The image name
      type: string
    - name: version
      description: The version
      type: string
    - name: make-image
      description: The build image
      type: string
      default: quay.io/okderators/bundle-tools:vdev
    - name: env-map
      description: The env map
      type: array
      default: []
  
  workspaces:
    - name: workspace
    - name: patches
  
  tasks:
    - name: clone-and-patch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.repo-ref)
        - name: verbose
          value: 'true'
        - name: subdirectory
          value: $(params.image-name)
      workspaces:
        - name: output
          workspace: workspace
        - name: patches
          workspace: patches

    - name: build
      runAfter: [ clone-and-patch ]
      taskRef:
        name: make-operand
      params:
        - name: image
          value: $(params.make-image)
        - name: subdirectory
          value: $(params.image-name)
        - name: image-name
          value: $(params.image-name)
        - name: image-registry
          value: $(params.base-image-registry)
        - name: version
          value: $(params.version)
        - name: env-map
          value: $(params.env-map[*])
      workspaces:
        - name: work
          workspace: workspace
