apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-operator-volume
  namespace: okd-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi