apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rbac.authorization.k8s.io/v1
  - ../../base/tekton.dev/tasks
  - ../../base/tekton.dev/pipelines
  - ../../base/tekton.dev/pv-pvc
namespace: okd-team

patchesJson6902:
- path: patches/patch-container-all-resources.yaml
  target:
    group: tekton.dev
    kind: Task
    name: container-all
    version: v1beta1

- path: patches/patch-bundle-all-resources.yaml
  target:
    group: tekton.dev
    kind: Task
    name: bundle-all
    version: v1beta1

patchesStrategicMerge:
  - patches/set_storage_class.yaml
    #- patches/set_pvc.yaml
