generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: rook-ceph-patch
    namespace: okd-team
    files:
      - 0001-OKDify.patch

resources:
  - repository.yaml
  - pvc.yaml