apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: console-plugin-deploy
  namespace: okd-team
spec:
  params:
    - name: base-image-registry
      description: The base image registry
      type: string
    - name: image-name
      description: The image name
      type: string
    - name: image-version
      description: The image version
      type: string

  workspaces:
    - name: src

  stepTemplate:
    name: task
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
    resources:
      limits:
        cpu: 800m
        memory: 2000Mi
      requests:
        cpu: 800m
        memory: 2000Mi

  steps:
    - name: lint
      image: docker.io/library/node:16
      imagePullPolicy: Always
      command: ["yarn"]
      args: ["run", "lint"]
      workingDir: /workspace/src
      workspaces:
        - name: src
          workspace: src

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace/src
      command: [ "/kaniko/executor" ]
      args: [ "--dockerfile=/workspace/src/Dockerfile", "--context=/workspace/src/",
              "--destination=$(params.base-image-registry)/$(params.image-name):v$(params.image-version)" ]
      workspaces:
        - name: src
          workspace: src
