apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: make
  namespace: okd-team
spec:
  params:
    - name: image
      description: The image to use for the build
      type: string
    - name: subdirectory
      description: The subdirectory to run the build in
      type: string
    - name: args
      description: The arguments to pass to the make command
      type: array
    - name: version
      description: The version to use for the build
      type: string
      default: ""
    - name: normalized-version
      description: The normalized version to use for the build
      type: string
      default: $(params.version)
    - name: env-map
      description: The env map
      type: string
      default: ""

  workspaces:
    - name: source
    - name: build-cache-root
      mountPath: /go/.cache
    - name: build-pkg
      mountPath: /go/pkg

  steps:
    - name: run
      imagePullPolicy: Always
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.image)
      args: ["$(params.args)"]
      script: |
        $(params.env-map) make $@
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      env:
        - name: "VERSION"
          value: "$(params.version)"
        - name: "NORM_VERSION"
          value: "$(params.normalized-version)"