apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: version-csv
  namespace: okd-team
spec:
  description: |
    This task finds the version of an operator from its ClusterServiceVersion.
  params:
    - name: location
      description: Location of cluster service version configuration
      type: string

  results:
    - name: version
      description: Version of operator

  workspaces:
    - name: source

  steps:
    - name: find-version
      image: docker.io/mikefarah/yq:4
      stdoutConfig:
        path: $(results.version.path)
      args: [".spec.version", "$(workspaces.source.path)/$(params.location)"]
    - name: strip-whitespace
      image: docker.io/bash:5
      script: |
        cat "$(results.version.path)" | sed -re 's/^[[:blank:]]+|[[:blank:]]+$//g' -e 's/[[:blank:]]+/ /g' | tr -d "\n" | tee "$(results.version.path)"