apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: version-npm
  namespace: okd-team
spec:
  description: |
    This task finds the version of an operator from its ClusterServiceVersion.
  params:
    - name: subdirectory
      description: Subdirectory inside the `source` Workspace to clone the repo into.
      type: string
      default: ""

  results:
    - name: version
      description: Version of operator

  workspaces:
    - name: source

  steps:
    - name: find-version
      image: docker.io/apteno/alpine-jq:latest
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      stdoutConfig:
        path: $(results.version.path)
      command: ["jq"]
      args: ["-r", ".version", "package.json"]
    - name: strip-whitespace
      image: docker.io/bash:5
      script: |
        cat "$(results.version.path)" | sed -re 's/^[[:blank:]]+|[[:blank:]]+$//g' -e 's/[[:blank:]]+/ /g' | tr -d "\n" | tee "$(results.version.path)"