apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: noobaa-core-repository
  namespace: okd-team
spec:
  url: https://github.com/noobaa/noobaa-core.git
  ref: main
  frequency: 5m
  type: github
  pipelineRef:
    name: operand-noobaa
    namespace: okd-team
    params:
      - name: repo-ref
        expression: commit.sha
      - name: repo-url
        expression: repoURL
      - name: patch-configmap
        expression: "'noobaa-core-patch'"
      - name: base-image-registry
        expression: "'quay.io/okderators'"
      - name: image-name
        expression: "'noobaa-core'"
    workspaces:
      - name: output
        persistentVolumeClaim:
          claimName: noobaa-core-volume