apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: ocs-metrics-exporter-repository
  namespace: okd-team
spec:
  url: https://github.com/red-hat-storage/ocs-operator.git
  ref: master
  frequency: 5m
  type: github
  pipelineRef:
    name: operator
    namespace: okd-team
    params:
      - name: repo-ref
        expression: commit.sha
      - name: repo-url
        expression: repoURL
      - name: base-image-registry
        expression: "'quay.io/okderators'"
      - name: image-name
        expression: "'ocs-metrics-exporter'"
      - name: image-version
        expression: "'dev'"
      - name: channel
        expression: "'dev'"
      - name: default-channel
        expression: "'stable'"
    workspaces:
      - name: output
        persistentVolumeClaim:
          claimName: ocs-metrics-exporter-volume
      - name: patches
        persistentVolumeClaim:
          claimName: ocs-metrics-exporter-patch